% Alejandro Gonzalez
% Basic plot util to check the timing of the disruption 
% and the UFO.
%
% If the dataset changes, so does the input function.
%
% TODO: use velocities as well when I get them.
%
% Changelog:
%	0.1 (AG): first version.

data_table = importfile('5th_8th_with_disr.csv');
unique_pulses = unique(data_table.Pulse);

hold on
for i = 1 : length(unique_pulses)
    jpn = unique_pulses(i);
    row_ind = find(data_table.Pulse == jpn);
    disr_time = data_table.Disruption(row_ind);
    if disr_time == 0
        continue
    end
    ufo_time = data_table.Time(row_ind);
    scatter(i, disr_time, 'red', 'filled');
    scatter(i, ufo_time, 'blue', 'filled');
end
hold off

function th8thwithdisr1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TH8THWITHDISR1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TH8THWITHDISR1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  th8thwithdisr1 = importfile("C:\Users\Admin\Documents\Doctorado\UFOs\data\5th_8th_with_disr.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Mar-2024 10:18:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Unnamed0", "Pulse", "OpCam", "Time", "ExpCam", "Disruption", "Comments"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Comments", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Comments", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["OpCam", "ExpCam"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["OpCam", "ExpCam"], "ThousandsSeparator", ",");

% Import the data
th8thwithdisr1 = readtable(filename, opts);

end
